type MorseType = {
    value: string
};

type Morse = {
    [key: string]: MorseType
}

export const morseDictionary: Morse = {
    A: { value: ".-" },
    B: { value: "-..." },
    C: { value: "-.-." },
    D: { value: "-.." },
    E: { value: "." },
    F: { value: "..-." },
    G: { value: "--." },
    H: { value: "...." },
    I: { value: ".." },
    J: { value: ".---" },
    K: { value: "-.-" },
    L: { value: ".-.." },
    M: { value: "--" },
    N: { value: "-." },
    O: { value: "---" },
    P: { value: ".--." },
    Q: { value: "--.-" },
    R: { value: ".-." },
    S: { value: "..." },
    T: { value: "-" },
    U: { value: "..-" },
    V: { value: "...-" },
    W: { value: ".--" },
    X: { value: "-..-" },
    Y: { value: "-.--" },
    Z: { value: "--.." },
    a: { value: ".-" },
    b: { value: "-..." },
    c: { value: "-.-." },
    d: { value: "-.." },
    e: { value: "." },
    f: { value: "..-." },
    g: { value: "--." },
    h: { value: "...." },
    i: { value: ".." },
    j: { value: ".---" },
    k: { value: "-.-" },
    l: { value: ".-.." },
    m: { value: "--" },
    n: { value: "-." },
    o: { value: "---" },
    p: { value: ".--." },
    q: { value: "--.-" },
    r: { value: ".-." },
    s: { value: "..." },
    t: { value: "-" },
    u: { value: "..-" },
    v: { value: "...-" },
    w: { value: ".--" },
    x: { value: "-..-" },
    y: { value: "-.--" },
    z: { value: "--.." },
    " ": { value: " / " },
    "1": { value: ".----" },
    "2": { value: "..---" },
    "3": { value: "...--" },
    "4": { value: "....-" },
    "5": { value: "....." },
    "6": { value: "-...." },
    "7": { value: "--..." },
    "8": { value: "---.." },
    "9": { value: "----." },
    "0": { value: "-----" },
    ".": { value: ".-.-.-" },
    ",": { value: "--..--" },
    "?": { value: "..--.." },
    "'": { value: ".----." },
    "!": { value: "-.-.--" },
    "/": { value: "-..-." },
    "(": { value: "-.--." },
    ")": { value: "-.--.-" },
    "&": { value: ".-..." },
    ":": { value: "---..." },
    ";": { value: "-.-.-." },
    "=": { value: "-...-" },
    "+": { value: ".-.-." },
    "-": { value: "-....-" },
    "_": { value: "..--.-" },
    '"': { value: ".-..-." },
    "$": { value: "...-..-" },
    "@": { value: ".--.-." },
};

// You can continue adding more characters as needed.
